### ISSUE TITLE
运行时出现报错：ReferenceError: tencentcloud is not defined

### ISSUE THREAD

**Issue by WenHe233** [Ninzore/Caster#3]
> 0|caster  | /home/xxxxxxxx/Downloads/Caster/plugin/translate.js:1
> 0|caster  | ReferenceError: tencentcloud is not defined
> 0|caster  |     at Object.<anonymous> (/home/wenhe/Downloads/Caster/plugin/translate.js:4:19)
> 0|caster  |     at Generator.next (<anonymous>)

**Comment by Ninzore** [comment]
没装依赖

**Comment by TeoZler** [comment]
发现问题了，在translate.js加了一行`const tencentcloud = require("tencentcloud-sdk-nodejs")`就好了

**Comment by WenHe233** [comment]
> 没装依赖

大概不是依赖的问题，`npm i`的时候有装`tencentcloud-sdk-nodejs`
发现问题了，在translate.js加了一行`const tencentcloud = require("tencentcloud-sdk-nodejs")`就好了
